### ISSUE TITLE
Proposed update to section 2.5

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa/RadioVOImplementation#11]
The current sentence: 
> Dataproduct_type “timeseries" may be ambiguous for dynamic spectra, so a dataproduct_subtype can be used, or a new dataproduct_type may be introduced.

could be replaced by:
> Dataproduct_type “timeseries" may be ambiguous for dynamic spectra, so a dataproduct_subtype can be used, or a new dataproduct_type may be introduced, following the EPNcore dataproduct_type list, which includes a _dynamic-spectrum_ type.

**Comment by Bonnarel** [comment]
and a new term in the product_type proposed vocabulary. Write a PR I will validate it
