### ISSUE TITLE
tittle suggestion : "Implementation review "

### ISSUE THREAD

**Issue by loumir** [ivoa/RadioVOImplementation#20]
I suggest to change the title to "Radio astronomy in the VO:  services implementation review" .

it reflects the review on all services considered in this IVOA Note.

usually , the Implementation Note document is more a way to explain what to do for implementing a new IVOA specification .

what do you think?

**Comment by BaptisteCecconi** [comment]
I think this capture very well the content of the document

**Comment by BaptisteCecconi** [comment]
Note from email thread: Yan Grange agrees too.

**Comment by Bonnarel** [comment]
I would like other authors to give their opinion.
It is true that the title Mireille is proposing is well adapted to the 
current content.
BUt the original idea was to have an implementation note.

So either we arer happy with changing a little bit the goal and we 
change the title
Or we keep the toitle and try to be more directive in the "main" section

Le 06/11/2021 à 11:58, Baptiste Cecconi a écrit :

**Comment by pahjbo** [comment]
I think that Implementation Review is closer to how the document has turned out.

**Comment by Bonnarel** [comment]
solved in PR #24
