### ISSUE TITLE
Authors of the note

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa/RadioVOImplementation#7]
The current author list refers to the _RadioIG members_. Shall we add names explicitly? 
I think it would be more fair to authors who participated in the document edition, in the preparation of the note through the discussion workshops.

**Comment by msdemlei** [comment]
On Thu, Jun 17, 2021 at 03:21:31AM -0700, Baptiste Cecconi wrote:
> The current author list refers to the _RadioIG members_. Shall we
> add names explicitly? 
> I think it would be more fair to authors who participated in the
> document edition, in the preparation of the note through the
> discussion workshops. 

Yeah, please don't have groups as authors.  It's hard to get this
right when a machine processes the bibliographic metadata, so
citations tend to look weird, and there's very little informative
value in having "...and the XY group" anyway.

        -- Markus

**Comment by ygrange** [comment]
seconding (thirding?) that :)

**Comment by Bonnarel** [comment]
OK, I will fix that ASAP. Additional authors will be : Baptiste Cecconi, Alan Loh, Yan Grange, Alessandra Zanichelli, James Dempsey, Felix Stoehr, Severin Gaudet, Mark Kettenis, Harro Verkouter, Andrea Wicenec, Paul Harrison (soon), and ????

**Comment by BaptisteCecconi** [comment]
For Pulsar contributions: Jean-Mathias Grießmeier

**Comment by Bonnarel** [comment]
This has been solved with last PR

**Comment by Bonnarel** [comment]
Issue can be closed.

**Comment by Bonnarel** [comment]
fixed in PR#17
