### ISSUE TITLE
Solar system (low frequency) radio astronomy Appendix

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa/RadioVOImplementation#8]
I propose a new appendix in #6 for Solar system low frequency radio astronomy (mostly dynamic spectrum data).

**Comment by molinaro-m** [comment]
Would solar radio polarimetry (not dynamic spectra, but nearly monochromatic solar monitoring) fit that one?

**Comment by BaptisteCecconi** [comment]
I guess so, please have a look to the appendix section of the PR.

**Comment by BaptisteCecconi** [comment]
Actually, I wrote _mostly_, since there are Solar radio imaging products (e.g., from Nancay Radio Heliograph).

**Comment by BaptisteCecconi** [comment]
@molinaro-m: the PR has been merged long ago. How ever, are you happy with the text, or to do you want an update for your comment ?
